
server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zl.pojo #\u6240\u6709entity\u522B\u540D\u7C7B\u6240\u5728\u5305

eureka:
  client:
    register-with-eureka: true #\u8868\u793A\u5C06\u81EA\u5DF1\u6CE8\u518C\u8FDBEurekaServer
    fetch-registry: true #\u4ECEEurekaServer\u6293\u53D6\u5DF2\u6709\u6CE8\u518C\u4FE1\u606F\uFF0C\u5355\u8282\u70B9\u65E0\u6240\u8C13\uFF0C\u96C6\u7FA4\u5FC5\u987Btrue\u624D\u80FD\u914D\u5408ribbon\u4F7F\u7528\u8D1F\u8F7D\u5747\u8861
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true #访问路径可以显示ip